#########################################
###    ESTABLECIMIENTOS API TESTING   ###
#########################################

### Crear establecimiento
POST http://localhost:3000/api-backend-prueba/establecimiento/crear
Content-Type: application/json

{
  "identificador": "campus-lincoyan",
  "nombre": "Campus Lincoyan",
  "direccion": "lincoyan 3222",
  "capacidad": 20
}

### Listar todos los establecimientos
GET http://localhost:3000/api-backend-prueba/establecimiento/listar

### Obtener establecimiento por ID
GET http://localhost:3000/api-backend-prueba/establecimiento/obtener/691f6de923d31003d07fb28f

### Obtener establecimiento por IDENTIFIFCADOR
GET http://localhost:3000/api-backend-prueba/establecimiento/obtener-por-identificador/lincoyan


### Acctualizar establecimiento
PUT http://localhost:3000/api-backend-prueba/establecimiento/actualizar/690d0039ca618e39c846a8ac
Content-Type: application/json

{
  "identificador": "cft4223",
  "nombre": "CFT tecnico",
  "direccion": "acacios 777",
  "capacidad": 20
}

